/*
  AltDrag 1.0 - localization by Jack Jin and alex310110

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  Do not edit this file! It is automatically generated from Translate.ini!
*/

struct strings zh_CN = {
 /* === translation info === */
  L"zh-CN",
  L"Chinese",
  L"简体中文",
  L"狂飙的小蜗牛",

 /* === app === */
  L"AltDrag",
  L"AltDrag (已禁用)",

  /* menu */
  L"启用",
  L"禁用",
  L"隐藏通知栏图标",
  L"有可用的更新！",
  L"设置(&S)",
  L"关于(&A)",
  L"退出(&X)",

 /* update */
  L"发现新版本！",
  L"有可用的新版本。打开 AltDrag 网站吗？",
  L"没有可用的更新。",

 /* === config === */
  L"AltDrag 配置",

 /* tabs */
  L"常规",
  L"鼠标和键盘",
  L"排除列表",
  L"增强",
  L"关于",

 /* general tab */
  L"通用设置",
  L"拖动时聚焦窗口 (&F)\nCtrl也可以聚焦到窗口",
  L"Win7 窗口贴边自动调整 (&N)",
  L"滚动非活动窗口 (&S)",
  L"MDI 支持 (&M)",
  L"自动吸附在:",
  L"禁止",
  L"到屏幕边缘",
  L"+ 在窗口外",
  L"+ 在窗口内",
  L"语言:",
  L"随系统自动启动",
  L"登录时启动 AltDrag (&T)",
  L"隐藏通知栏图标 (&H)",
  L"提升至超级用户权限 (&E)",
  L"注意，除非你完全禁用 UAC，否则每次登录都会出现 UAC 提示。",
  L"提升 (&L)",
  L"已经提升",
  L"这会创建一个新的以超级用户权限运行的 AltDrag 实例。以允许 AltDrag 管理其他以超级用户权限运行的程序。\n\n。在弹出 UAC 提示时，你必须同意 AltDrag 以超级用户权限运行",
  L"提升过程终止。",
  L"注意: 设置改动后会立即保存！",

 /* input tab */
  L"鼠标动作",
  L"鼠标左键:",
  L"鼠标中键:",
  L"鼠标右键:",
  L"鼠标第 4 键:",
  L"鼠标第 5 键:",
  L"滚动:",
  L"通过鼠标中键单击标题栏来降低窗口层次(&L)",

 /* actions */
  L"移动窗口",
  L"更改大小",
  L"关闭窗口",
  L"最小化",
  L"降低窗口",
  L"窗口置顶",
  L"居中窗口",
  L"无动作",
  L"Alt+Tab",
  L"更改音量",
  L"透明度",

 /* hotkeys */
  L"热键",
  L"左 Alt 键 (&E)",
  L"右 Alt 键 (&R)",
  L"左 Win 键 (&W)",
  L"右 Win 键 (&I)",
  L"左 Ctrl 键 (&C)",
  L"右 Ctrl 键 (&T)",
  L"你可以通过修改 INI 配置文件来加入任何键！\n用 Shift 键使窗口间进行吸附。",

 /* blacklist tab */
  L"排除列表设置",
  L"进程黑名单:",
  L"排除列表:",
  L"自动吸附列表:",
  L"排除列表具体如何工作，请参阅 <a href=\"https://stefansundin.github.io/altdrag/doc/blacklist.html\">AltDrag 网站维基</a>！",
  L"辩识窗口",
  L"全用此工具来辩识窗口的类名，以便于你在排除列表或自动吸附列表中进行添加。",

 /* advanced tab */
  L"增强设置",
  L"在普通移动中吸附窗口 (&E)。\n与自动吸附同时工作！",
  L"注意这个特性不是 100% 安全的，因为他会对其他进程进行挂接或类似操作。",
  L"自动检查更新 (&U)",
  L"为 Beta 版检查更新 (&B)",
  L"检查更新",
  L"AltDrag 的设置保存在 AltDrag.ini。有少量配置可以通过手工编辑此文件来更改。",
  L"打开INI文件(&I)",

 /* about tab */
  L"关于 AltDrag",
  L"版本 1.1",
  L"作者: Stefan Sundin",
  L"AltDrag 是自由和开源软件！\n欢迎重新发布！",
  L"捐赠 (&D)",
  L"翻译贡献者",

 /* === misc === */
  L"在禁用 AltDrag 时发生错误。这可能是因为 Windows 已经禁用了在禁用 AltDrag 的勾子而引起的。\n\n如果是第一次发生这种情况，你可以安全的忽略并继续使用在禁用 AltDrag。\n\n如果这个错误重复出现，你可以阅读 wiki 来防范这种情况的再次发生。 (在About页上寻找'在禁用 AltDrag 意外停止工作')",
};
